"""fix

Revision ID: 00642694302a
Revises: d8c45ccfedec
Create Date: 2026-06-04 13:25:37.863415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00642694302a'
down_revision: Union[str, Sequence[str], None] = 'd8c45ccfedec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'templates', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'templates', type_='foreignkey')
    op.drop_column('templates', 'user_id')
    # ### end Alembic commands ###
