"""extra column

Revision ID: 39ae4fadd434
Revises: ab358cf2fe30
Create Date: 2026-06-09 07:09:47.205527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39ae4fadd434'
down_revision: Union[str, Sequence[str], None] = 'ab358cf2fe30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    "notifications",
    sa.Column(
        "retry_count",
        sa.Integer(),
        nullable=False,
        server_default="0"
    )
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'retry_count')
    # ### end Alembic commands ###
