"""extra column

Revision ID: 8962400b8ff7
Revises: 0175d258ac22
Create Date: 2026-06-06 17:34:23.592181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8962400b8ff7'
down_revision: Union[str, Sequence[str], None] = '0175d258ac22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    "users",
    sa.Column(
        "is_admin",
        sa.Boolean(),
        nullable=False,
        server_default="false"
    )
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
