"""fix

Revision ID: d94262d342ce
Revises: 00642694302a
Create Date: 2026-06-04 13:36:33.241573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd94262d342ce'
down_revision: Union[str, Sequence[str], None] = '00642694302a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('templates_user_id_fkey'), 'templates', type_='foreignkey')
    op.drop_column('templates', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('templates_user_id_fkey'), 'templates', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
